language: cpp

git:
  submodules: false

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libopenal-dev libvorbis-dev libglew-dev

script: cmake . && make

notifications:
  irc:
    channels:
      - "irc.euirc.net#hswgt.ai"
    use_notice: true
    skip_join: true
